name: infra_env_cuda
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch>=2.3
  - pytorch-cuda=12.1
  - git
  - curl
  - ca-certificates
  - openssl
  - tzdata
  - pip:
      - fastapi>=0.115
      - uvicorn[standard]>=0.30
      - pydantic>=2.7
      - python-dotenv>=1.0
      - orjson>=3.10
      - httpx>=0.27
      - tenacity>=8.2
      - rich>=13.7
      - structlog>=24.1
      - loguru>=0.7
      # Retrieval stack
      - qdrant-client>=1.9
      - opensearch-py>=2.5
      - rank-bm25>=0.2
      # NLP / embeddings / rerankers
      - openai>=1.40
      - tiktoken>=0.7
      - sentence-transformers>=2.7
      - transformers>=4.43
      - accelerate>=0.33
      - spacy>=3.7
      - spacy-lookups-data>=1.0
      - rapidfuzz>=3.9
      # Parsing & PDF/XML
      - pymupdf>=1.24
      - pdfplumber>=0.11
      - lxml>=5.2
      - beautifulsoup4>=4.12
      - unstructured>=0.15
      - pytesseract>=0.3
      # Data & utils
      - pandas>=2.2
      - numpy>=1.26
      - pyarrow>=16.1
      - tqdm>=4.66
      # Drafting / assembly
      - jinja2>=3.1
      - python-docx>=1.1
      - diff-match-patch>=20230430
      # Orchestration (pick one or both)
      - llama-index>=0.11
      - langchain>=0.2
      - langchain-community>=0.2
      # Validation / rules
      - jsonschema>=4.22
      - pydantic-core>=2.18
      # Observability & testing
      - opentelemetry-sdk>=1.25
      - opentelemetry-instrumentation-fastapi>=0.46
      - pytest>=8.3
      - pytest-asyncio>=0.23
      # Dev tools
      - black>=24.4
      - ruff>=0.5
      - mypy>=1.10
      - types-requests>=2.32