name: infra_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - git
  - curl
  - ca-certificates
  - openssl
  - tzdata
  - pip:
      - fastapi>=0.100
      - uvicorn[standard]>=0.25
      - pydantic>=2.5
      - python-dotenv>=1.0
      - orjson>=3.9
      - httpx>=0.25
      - tenacity>=8.2
      - rich>=13.0
      - structlog>=23.0
      - loguru>=0.7
      # Retrieval stack
      - qdrant-client>=1.7
      - opensearch-py>=2.3
      - rank-bm25>=0.2
      # NLP / embeddings / rerankers
      - openai>=1.30
      - tiktoken>=0.5
      - sentence-transformers>=2.5
      - transformers>=4.35
      - accelerate>=0.25
      - torch>=2.1
      - spacy>=3.6
      - rapidfuzz>=3.5
      # Parsing & PDF/XML
      - pymupdf>=1.23
      - pdfplumber>=0.10
      - lxml>=4.9
      - beautifulsoup4>=4.11
      - unstructured>=0.10
      - pytesseract>=0.3
      # Data & utils
      - pandas>=2.0
      - numpy>=1.24
      - pyarrow>=14.0
      - tqdm>=4.65
      # Drafting / assembly
      - jinja2>=3.1
      - python-docx>=0.8
      - diff-match-patch>=20200713
      # Orchestration - using compatible versions
      - llama-index>=0.9,<0.11
      - langchain>=0.1,<0.2
      - langchain-community>=0.0.20,<0.2
      # Validation / rules
      - jsonschema>=4.17
      - pydantic-core>=2.10
      # Observability & testing - using compatible versions
      - opentelemetry-sdk>=1.20,<1.25
      - pytest>=7.4
      - pytest-asyncio>=0.21
      # Dev tools
      - black>=23.0
      - ruff>=0.1
      - mypy>=1.5
      - types-requests>=2.31
      # Database drivers
      - psycopg[binary]>=3.2
      # Remote execution
      - modal-client>=0.64
